const userRoutes = {
    userSignup: '/user/signup',
    verifyOtp: '/user/verifyotp',
    resendOtp:'/user/resendotp',
    userLogin:'/user/userlogin',
    forgotPassword: '/user/forgotpassword',
    verifyForgot:'/user/verifyforgotpassword',
    changedPassword:'/user/changedpassword',
    googleSignin:'/user/google',
    profilepage:'/user/profile',
    profileEdit:'/user/profileedit',
    updateProfile:'/user/updateprofile',
    updateprofilePassword:'/user/updatepassword',
    emailchange:'/user/emailchange',
    verifyEmail:'/user/verifyEmail',
    Course:'/user/course',
    GetCourse:'/user/getcourse',
    GetCourseAcess: '/user/courseAccess',
    GetUsers: '/user/userbyid',
    GetPayment:'/user/getpayment',
    GetVideoCall:'/user/getvideocallkey',
    Payment:'/user/payment',
    OrderPost:'/user/orderpost',
    getCourse:'/user/CourseAccess',
    getChapters:'/user/getchapters',
    GetCategory:'/user/category',
    EnrolledCourses:'/user/enrolledview',
    ReviewSubmit:'/user/reviewsubmit',
    EditReviewSubmit: '/user/editreview',
    CompletedChapterView:'/user/completedChapterview',
    CompletedLessonsView:'/user/completedlessonview',
    CompletedChaptersPost:'/user/completedchapter',
    CompletedLessonPost:'/user/completedlesson',
    fetchENrolled:'/user/enrolled',
    QuestionAnswer:'/user/answer',
    findTutors:'/user/findTutorById',
    GetCourses:'/user/course',
    TutorsChat:'/user/tutorschat',
    newConverSationWithTutor:'/user/newConversation',
    GetMessagesUser:'/user/getMessages',
    NewMessageForUser:'/user/newMessage',
    getConversationTutor:'/user/getConversation',
    userLogout:'/user/logout',
    googleAuth:'/user/google',
    searchCourse:'/user/search'

    


}

export default userRoutes;